// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace MLModel1_ConsoleApp1
{
    public partial class MLModel1
    {
        /// <summary>
        /// model input class for MLModel1.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"column1")]
            public float Column1 { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"key")]
            public string Key { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"fare_amount")]
            public float Fare_amount { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"pickup_datetime")]
            public string Pickup_datetime { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"pickup_longitude")]
            public float Pickup_longitude { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"pickup_latitude")]
            public float Pickup_latitude { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"dropoff_longitude")]
            public float Dropoff_longitude { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"dropoff_latitude")]
            public float Dropoff_latitude { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"passenger_count")]
            public float Passenger_count { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModel1.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"column1")]
            public float Column1 { get; set; }

            [ColumnName(@"key")]
            public float[] Key { get; set; }

            [ColumnName(@"fare_amount")]
            public float Fare_amount { get; set; }

            [ColumnName(@"pickup_datetime")]
            public float[] Pickup_datetime { get; set; }

            [ColumnName(@"pickup_longitude")]
            public float Pickup_longitude { get; set; }

            [ColumnName(@"pickup_latitude")]
            public float Pickup_latitude { get; set; }

            [ColumnName(@"dropoff_longitude")]
            public float Dropoff_longitude { get; set; }

            [ColumnName(@"dropoff_latitude")]
            public float Dropoff_latitude { get; set; }

            [ColumnName(@"passenger_count")]
            public float Passenger_count { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLModel1.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
