
// This file was auto-generated by ML.NET Model Builder. 

using MLModel1_ConsoleApp1;

// Create single instance of sample data from first line of dataset for model input
MLModel1.ModelInput sampleData = new MLModel1.ModelInput()
{
    Column1 = 27835200F,
    Key = @"2009-07-17 20:04:56.0000002",
    Pickup_datetime = @"2009-07-17 20:04:56 UTC",
    Pickup_longitude = -73.994354F,
    Pickup_latitude = 40.728226F,
    Dropoff_longitude = -73.99471F,
    Dropoff_latitude = 40.750324F,
    Passenger_count = 1F,
};



Console.WriteLine("Using model to make single prediction -- Comparing actual Fare_amount with predicted Fare_amount from sample data...\n\n");


Console.WriteLine($"Column1: {27835200F}");
Console.WriteLine($"Key: {@"2009-07-17 20:04:56.0000002"}");
Console.WriteLine($"Fare_amount: {7.7F}");
Console.WriteLine($"Pickup_datetime: {@"2009-07-17 20:04:56 UTC"}");
Console.WriteLine($"Pickup_longitude: {-73.994354F}");
Console.WriteLine($"Pickup_latitude: {40.728226F}");
Console.WriteLine($"Dropoff_longitude: {-73.99471F}");
Console.WriteLine($"Dropoff_latitude: {40.750324F}");
Console.WriteLine($"Passenger_count: {1F}");


// Make a single prediction on the sample data and print results
var predictionResult = MLModel1.Predict(sampleData);
Console.WriteLine($"\n\nPredicted Fare_amount: {predictionResult.Score}\n\n");

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

